trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments:  'backend/backend.csproj --configuration release --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: backend
